### ISSUE TITLE
I am getting this error when trying to go to a table view in my VC.

### ISSUE THREAD

**Issue by magiusdarrigo** [kyleweiner/KWStepper#13]
`    /// :nodoc:
    required public init?(coder aDecoder: NSCoder) {
        fatalError("KWStepper: NSCoding is not supported!")
    }`

what could this be?
Thanks!

**Comment by magiusdarrigo** [comment]
BTW, it is the cell in the table view that uses the kwstepper protocal.

**Comment by kyleweiner** [comment]
Hi @magiusdarrigo,

Are you trying to initialize the stepper from a storyboard? This isn’t supported. However, you can follow this bare-bones example for your `UITableViewCell` subclass:

```
import UIKit
import KWStepper

class KWStepperCell: UITableViewCell {
    @IBOutlet weak var leftButton: UIButton!
    @IBOutlet weak var rightButton: UIButton!

    lazy var stepper = KWStepper(
        decrementButton: leftButton,
        incrementButton: rightButton
    )
    .wraps(true)
    .stepValue(2)
}
```

Please share some code if this doesn't solve your issue :)
