### ISSUE TITLE
Deployment Target set to iOS 9 in latest release 

### ISSUE THREAD

**Issue by rmzr7** [kyleweiner/KWStepper#2]

**Comment by kyleweiner** [comment]
@remzr7 Thanks for reporting another issue! Can you elaborate on your problem? Specifically, is it with the [podspec](https://github.com/kyleweiner/KWStepper/blob/2.0.0/KWStepper.podspec#L12) for [version 2.0.0](https://github.com/kyleweiner/KWStepper/tree/2.0.0)?

**Comment by sealemar** [comment]
I think the question is why is it set to iOS 9? Only one statement requires `swift 2` -- `guard`, which could be replaced with `if`.

I couldn't find any official documentation on what iOS versions does Swift 2 support. If it has the same coverage as the original Swift, then iOS 7 should be enough. See [Apple Blog Post](https://developer.apple.com/swift/blog/?id=2)

**Comment by kyleweiner** [comment]
@sealemar Thanks for the input. Your point about the  `guard` statement is a good one. Perhaps I should have used a different branch for this release. That said, [version 1.2.1](https://github.com/kyleweiner/KWStepper/releases/tag/1.2.1) is still a perfectly viable option for projects that aren't ready to support Swift 2.0 or may be using an older version of iOS; I will gladly revisit this issue if that's ever not the case. Ideally, KWStepper should begin following the conventions introduced in Swift 2.0 and using [`guard`](https://github.com/kyleweiner/KWStepper/blob/master/KWStepper/KWStepper.swift#L212) makes the intent clearer in this case. I will consider reverting the  [`guard`](https://github.com/kyleweiner/KWStepper/blob/master/KWStepper/KWStepper.swift#L212) statement and [podspec](https://github.com/kyleweiner/KWStepper/blob/2.0.0/KWStepper.podspec#L12) though.

**Comment by sealemar** [comment]
@kyleweiner, `guard` is fine. [Swift 2.0](https://developer.apple.com/swift/?cid=wwa-us-kwg-features-com) looks like is simply a newer version of the compiler which shouldn't directly affect iOS availability. That said iOS 7.0 should be enough as a target version. Please, confirm.

**Comment by kyleweiner** [comment]
Ah, I believe you are correct. Note that CocoaPods only supports [Swift on iOS 8 and newer](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) though. Perhaps `s.ios.deployment_target = "8.0"` would be fine. Either way, I've been unable to successfully `pod spec lint` since updating the project to Swift 2.0. I'm looking into that.

**Comment by sealemar** [comment]
Yeah, iOS 8.0 requirement comes from [Dynamic Frameworks on iOS](http://blog.cocoapods.org/CocoaPods-0.36/) support for which came only in iOS 8.0.

Anyway, [84% devices as of 7/9/2015](https://developer.apple.com/support/app-store/) support iOS 8.0, that is [everything starting from iPhone 4S and iPad 2](http://www.cnet.com/news/apple-devices-that-arent-compatible-with-ios-8/). That accounts for all devices which came [after October 2011](https://www.apple.com/pr/library/2011/10/04Apple-Launches-iPhone-4S-iOS-5-iCloud.html).

**Comment by kyleweiner** [comment]
The latest podspec has been updated to target iOS 8.
