### ISSUE TITLE
Swift project XCode CocoaPods isn't working

### ISSUE THREAD

**Issue by sealemar** [kyleweiner/KWStepper#3]
I added `pod 'KWStepper'` to `Podfile`, ran `pod install`. Successfully imported `import KWStepper` to the file where I'm trying to use KWStepper. It can't find `KWStepperDelegate` and `KWStepper` even though the framework is attached.

**Comment by kyleweiner** [comment]
Thanks for reporting this issue! Support for CocoaPods should be fixed in [version 1.2.2](https://github.com/kyleweiner/KWStepper/releases/tag/1.2.2). Please give it a try and let me know how it goes.

**Comment by sealemar** [comment]
There are a couple of things about the code that are stopping me from trying it:
1. Swift 2.0 support will come in XCode 7. `guard` is a part of Swift 2.0. I've tried a pre-release version of XCode several times in the past and I don't want to try it for writing prod code again. Simply put - pre-release means it doesn't have to behave properly.
2. `NSException` is quiet odd in Swift world. [Swift 2.0 error handling](http://austinzheng.com/2015/06/08/swift-2-control-flow/) is about conforming to `ErrorType` protocol. `NSException` is a native exception and can only be caught from Objective-C. Of course, the community has developed some workarounds, like [SwiftTryCatch](https://github.com/williamFalcon/SwiftTryCatch) which is discussed in [that blog post](https://medium.com/swift-programming/adding-try-catch-to-swift-71ab27bcb5b8).
   Another approach to consider is [assertionFailure](http://swiftdoc.org/func/assertionFailure/). Two _possible_ downsides of that: 
   - it does nothing in release 
   - there is no way to handle that (_but how can you handle those cases in your code gracefully anyway?_)

**Comment by kyleweiner** [comment]
@sealemar I understand your position here.
1. You'll be pleased to know that Xcode 6.4 still works, as Swift 2.0 is no longer a requirement in [version 1.2.2](https://github.com/kyleweiner/KWStepper/releases/tag/1.2.2). I'm waiting until Xcode 7 is out of beta to use `guard` in a production release.
2. I agree and intend to update to Swift 2.0 error handling down the road. KWStepper only uses [`NSException`](https://github.com/kyleweiner/KWStepper/blob/master/Source/KWStepper.swift#L91) in setters though. My understanding is that [marking as "throws"](https://forums.developer.apple.com/thread/4289) isn't supported for setters. Hopefully, this will be implemented soon.

Anyway, I believe this issues is resolved, but please let me know if you encounter any problems.

**Comment by sealemar** [comment]
As for the number 2 the protocol is not going to support setters since according to `ErrorType` protocol, a function must return a non-void result.
