### ISSUE TITLE
An opportunity 

### ISSUE THREAD

**Issue by Ahmedshubber** [kyleweiner/KWStepper#4]
Hello, I need help finishing an app. If you can help me, Id love to tell you the idea. Its a great idea and very unique. I'm 60% done with the app and its one of a kind. If your interested in hearing the app, please email me back. I emailed you because of the project examples you have on GitHub. Thank you and hope to hear back from you.

**Comment by kyleweiner** [comment]
@Ahmedshubber Thanks for reaching out. You can email me directly at 28260b6d@opayq.com.
