### ISSUE TITLE
Callback until long press end

### ISSUE THREAD

**Issue by OuSS-90** [kyleweiner/KWStepper#8]
Hi, thank you for this awesome library
Is there a way to to have callback until long press finish ? cause i use backend call

**Comment by kyleweiner** [comment]
Hi, @OuSS-90. Thanks for the kind words. I'll add a `longPressEnded` callback (that executes immediately after a long press gesture ends) in the next release.

**Comment by OuSS-90** [comment]
Thank you 👍

**Comment by kyleweiner** [comment]
@OuSS-90 Check out [v2.4.0 ](https://github.com/kyleweiner/KWStepper/releases/tag/2.4.0)when you have a moment.

**Comment by OuSS-90** [comment]
Thank you very much 👍

**Comment by OuSS-90** [comment]
I fixed some code for longPress.
When there is long press, usually we don't want increment and decrement to be called so i added this code in both incrementValue() and decrementValue():

```
// Increment function
if longPressTimer == nil {
   delegate?.KWStepperDidIncrement?()
    incrementCallback?(self)
 }

// decrement function
if longPressTimer == nil {
     delegate?.KWStepperDidDecrement?()
     decrementCallback?(self)
} 
```

basically i call delegate only if there is no longpress

**Comment by kyleweiner** [comment]
Thanks for the update. If that’s what you’re after, a flag to indicate when a long press gesture is happening would make more sense. Then, you can guard against doing additional work (such as hitting the backend) in your callbacks. Or, you can try https://github.com/kyleweiner/KWStepper/pull/7#issuecomment-301321280, which avoids needing to concern yourself with the long press gesture entirely. For the former, please feel free to open another issue or submit a pull request. I'm not certain this feature is within the scope of the project though.
